### ISSUE TITLE
Backquotes in example description forcing new line

### ISSUE THREAD

**Issue by Ethiraric** [ostera/tldr.jsx#16]
Hi,

On pages like `history`, the example markdown contains embedded backquotes (surrounding `bash`):

    - Clear the commands history list (only for `bash`)

The client reads it as a command inserts a new line before and after.

The output looks something like :

    Clear the commands history list (only for
    bash
    )

Cordially

**Comment by ostera** [comment]
hey @Ethiraric thanks for taking the time to make an issue. This just got fixed a few seconds ago here: https://github.com/ostera/tldr.jsx/commit/a38726af7e44e9fcdcf4db5a5e83e774d7ee22ce
