### ISSUE TITLE
This app is well behind the official tl;dr at https://github.com/tldr-pages/tldr-pages.github.io

### ISSUE THREAD

**Issue by StewAlexanderACC** [ostera/tldr.jsx#160]
Please see my recently closed ticket [#37](https://github.com/tldr-pages/tldr-pages.github.io/issues/37) at the official tldr-pages github account.

This app is woefully behind the true repo, can you please do a pull from their https://github.com/tldr-pages/tldr/tree/master/pages to get the latest pages...

Or how about setting up a curl or wget script to pull from their regularly?

Anyway this app is out-of-date

**Comment by ostera** [comment]
Hi @StewAlexanderACC, the app pulls an index of command from Github every time it loads. The index is here: https://api.github.com/repos/tldr-pages/tldr-pages.github.io/contents/assets/index.json?ref=master

With regard to the issue you link, the Linux command can be found here: https://tldr.ostera.io/linux/ss
