### ISSUE TITLE
OpenSearch Description

### ISSUE THREAD

**Issue by BenjaminHae** [ostera/tldr.jsx#24]
How about adding a OpenSearch Description  Document.
Basically just a xml file telling the browser how to search in the tldr pages.
So I could enter the url of the webpage in chromium press tab write "git tag" press enter and I would be on the according tldr-page.
Further information: http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_description_document0

**Comment by ostera** [comment]
@BenjaminHae so I followed the specs and looked up how Github did their integration, but it doesn't seem to be working. Any advice?

**Comment by ostera** [comment]
Ah, according to this: https://code.google.com/p/chromium/issues/detail?id=58801#c3 and this: http://dev.chromium.org/tab-to-search, it will work automatically for a root domain, but not for a path.

**Comment by ostera** [comment]
I'll make a point to include a "Install search in your browser" link/button during the redesign, leaving this open for further reference.

**Comment by igorshubovych** [comment]
@ostera as far as I understood those specs we don't need .com domain. we can host all of this (your tool) on tldr-pages.github.io.

**Comment by ostera** [comment]
@igorshubovych as long as it's pathless then it's fine. We can add the OpenSearch spec at the `tldr-pages.github.io` level and have it forward the searches to `ostera.io/tldr.jsx`. I'll submit a PR.

**Comment by igorshubovych** [comment]
how about just hosting tldr.jsx on tldr-pages.github.io?

**Comment by ostera** [comment]
Will be the exact same unless we make tldr-pages.github.io be the web-client. It can't have a path.

So `tldr-pages.github.io/tldr.jsx` won't work either.

**Comment by igorshubovych** [comment]
yes, but your client is just JS, you can include that JS/CSS into main page.

**Comment by ostera** [comment]
If we did, then on every new build we'd have to manually update the site. Having an iframe that loads the page saves us a lot of pain and still maintains the tldr-pages being the tldr-pages.

**Comment by igorshubovych** [comment]
We can push only certain (stable) versions on site.

**Comment by ostera** [comment]
I work on feature branches (see my PR's to this repo), the master branch will always be the latest stable version of tldr.jsx

**Comment by ostera** [comment]
Anywho, this is no longer about the OpenSearch. The file is there and I'll include it as an option if we don't use a domain for it, and if we do it'll just work. Closing now.
