### ISSUE TITLE
Link for editing remains after you change the command

### ISSUE THREAD

**Issue by igorshubovych** [ostera/tldr.jsx#28]
Steps to reproduce:
1. Open the page
2. Insert "ln".
3. Wait for page to load, notice the link to edit ln.md page.
4. Press "BackSpace" in the search field.
5. The page is updated to "No such command", but the link to edit ln.md remains.

https://monosnap.com/file/0atBOhRWgXGHY6n6oRKP41iQwuBRdw

**Comment by ostera** [comment]
Noted! Thanks :)
