### ISSUE TITLE
http://www.ostera.io/tldr.jsx/ Broken

### ISSUE THREAD

**Issue by TechplexEngineer** [ostera/tldr.jsx#46]
http://www.ostera.io/tldr.jsx/ should probably redirect to the new? site: https://tldr.ostera.io/

**Comment by ostera** [comment]
@TechplexEngineer good catch! I'll fix that now.

**Comment by ostera** [comment]
A naive fix is in place, using an `<meta http-equiv="Refresh" ...>`.

I'll look into a better solution for this, but since the site was previously hosted on Github Pages I doubt there's a lot of flexibility when it comes to redirections.

Thanks again for reporting this 👍
