### ISSUE TITLE
Styling Search Result

### ISSUE THREAD

**Issue by liuderchi** [ostera/tldr.jsx#68]
Maybe it can enhance readability by adding different color to `<code>` element, like in stackoverflow.

example:
![demo](https://cloud.githubusercontent.com/assets/4994705/17543304/36195f08-5f02-11e6-8db4-88c1f20f5cab.jpg)

**Comment by ostera** [comment]
how does this look?

<img width="545" alt="screen shot 2016-08-12 at 8 53 27 pm" src="https://cloud.githubusercontent.com/assets/854222/17633703/f3ba5b20-60ce-11e6-9109-f9187aa21726.png">

**Comment by waldyrious** [comment]
I like it @ostera :)

**Comment by liuderchi** [comment]
I think it's now easier to read. :+1:
