### ISSUE TITLE
Needless horizontal scroll on small screens

### ISSUE THREAD

**Issue by zdroid** [ostera/tldr.jsx#72]
There's needless horizontal scroll in [tldr site's iframe](https://tldr-pages.github.io/), as well as other small-size screens.

![Display bug](https://cloud.githubusercontent.com/assets/2725611/19014933/31ff486c-87fa-11e6-854d-480c188ec4f5.png)

It looks like GitHub's stargazers button causes the issue. Can you please check it out?

**Comment by ostera** [comment]
Hey, yeah, I've been meaning to address the layout on #64, but haven't found time yet to sit down and do it.  

With that said, it seems to look fine on iPhone's screens (both portrait and landscape) as the Stargazers are hidden. What phone are you looking this from? Screen size?

**Comment by zdroid** [comment]
It's fine on my 5.2" phone with Full HD resolution, but I noticed it on my older phone with 4" qHD screen. Anyway, the matter is mostly on tldr's site as its size is very small.

**Comment by zdroid** [comment]
Most likely solved now.
