### ISSUE TITLE
cannot display help for apt-get

### ISSUE THREAD

**Issue by severak** [ostera/tldr.jsx#75]
cannot display help for apt-get command, probably dash brokes index.

**Comment by ostera** [comment]
Hi! It's not a bug, it's a feature 😝 

Fortunately, it is accessible but it has to be namespaced with the platform: https://tldr.ostera.io/linux/apt-get

Related to #70 and #60, `tldr.jsx` should know better than this! I'll close this but keep it linked to the other one so it doesn't get lost.

Thanks!

**Comment by severak** [comment]
`apt-get` is not available for platforms other than linux. So it should display even without prefix IMHO.

**Comment by ostera** [comment]
Yeah, we agree on that. The two linked issues are directly related to this issue.
